// Generated by `pracht typegen`. Do not edit manually.
import { createHref } from "@pracht/core";
import type { HrefRouteDefinition } from "@pracht/core";

export const routes = [
  {
    id: "home",
    path: "/",
  },
  {
    id: "basic",
    path: "/basic",
  },
  {
    id: "parallel",
    path: "/parallel",
  },
  {
    id: "nested",
    path: "/nested",
  },
  {
    id: "out-of-order",
    path: "/out-of-order",
  },
  {
    id: "grid",
    path: "/grid",
  },
] as const satisfies readonly HrefRouteDefinition[];

export const href = createHref(routes);
