// Generated by `pracht typegen`. Do not edit manually.
import "@pracht/core";
import type { CapabilityClientMethod } from "@pracht/core";

declare module "@pracht/core" {
  interface Register {
    capabilities: Record<never, never>;
    capabilityClient: Record<never, never>;
  }
}

export {};
