// Generated by `pracht typegen`. Do not edit manually.
import "@pracht/core";
import type { ApiRouteMethodMap, RouteLoaderData, RouteParamInput, SearchParamsInput } from "@pracht/core";

declare module "@pracht/core" {
  interface Register {
    routes: {
      "home": {
        path: "/";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/home")>;
      };
      "basic": {
        path: "/basic";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/basic")>;
      };
      "parallel": {
        path: "/parallel";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/parallel")>;
      };
      "nested": {
        path: "/nested";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/nested")>;
      };
      "out-of-order": {
        path: "/out-of-order";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/out-of-order")>;
      };
      "grid": {
        path: "/grid";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/grid")>;
      };
      "edge-cases": {
        path: "/edge-cases";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/edge-cases")>;
      };
    };
    apiRoutes: {
      "/api/health": {
        path: "/api/health";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/health")>;
      };
      "/api/no-js": {
        path: "/api/no-js";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/no-js")>;
      };
    };
  }
}

export {};
